# Generated by Django 4.1.5 on 2023-02-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID дела в BX24')),
                ('COMPLETED', models.CharField(choices=[('Y', 'Завернено'), ('N', 'Не завершено')], max_length=1, verbose_name='Заершено дело или нет')),
                ('DIRECTION', models.CharField(choices=[('0', '-'), ('1', 'Входящее'), ('2', 'Исходящее')], db_index=True, max_length=1, verbose_name='Направление дела (входящее/исходящее)')),
                ('TYPE_ID', models.CharField(choices=[('1', 'Встреча'), ('2', 'Звонок'), ('3', 'Задача'), ('4', 'Письмо')], db_index=True, max_length=1, verbose_name='Тип дела (встреча/звонрок/...)')),
                ('STATUS', models.CharField(choices=[('0', '-'), ('1', '-'), ('2', 'Ожидается'), ('3', 'Завершено'), ('4', 'Завершено автоматически')], max_length=1, verbose_name='Статус дела')),
                ('OWNER_TYPE_ID', models.CharField(blank=True, choices=[('1', 'Лид'), ('2', 'Сделка'), ('3', 'Контакт'), ('4', 'Компания')], max_length=1, null=True, verbose_name='Тип сущности к которой привязан звонок')),
                ('OWNER_ID', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID сущности к которой привязан звонок')),
                ('OWNER_NAME', models.CharField(blank=True, max_length=950, null=True, verbose_name='Название сущности к которой привязан звонок')),
                ('CREATED', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата создания дела')),
                ('END_TIME', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения дела')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Дело не удалено из Битрикс24')),
                ('DURATION', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Длительность звонка')),
                ('CALL_START_DATE', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата начала звонка')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID компании в BX24')),
                ('TITLE', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Название компании')),
                ('DATE_CREATE', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('ADDRESS', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес компании')),
                ('REVENUE', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Годовой оборот')),
                ('INDUSTRY', models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Сфера деятельности')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Отрасль')),
                ('region', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Регион')),
                ('source', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Источник компании')),
                ('number_employees', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество сотрудников')),
                ('district', models.CharField(blank=True, max_length=150, null=True, verbose_name='Район области')),
                ('main_activity', models.CharField(blank=True, max_length=500, null=True, verbose_name='Основной вид деятельности')),
                ('other_activities', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Другие виды деятельности')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Чистая прибыль')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Компания активна (не удалена)')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='ИНН компании')),
                ('requisite_region', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Реквизит - район')),
                ('requisites_city', models.CharField(blank=True, db_index=True, max_length=750, null=True, verbose_name='Реквизит - город')),
                ('requisites_province', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Реквизит - область')),
                ('date_last_communication', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней коммуникации')),
                ('summa_by_company_success', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, null=True, verbose_name='Сумма успешных сделок')),
                ('summa_by_company_work', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, null=True, verbose_name='Сумма сделок в работе')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID направления в BX24')),
                ('VALUE', models.CharField(max_length=50, verbose_name='Название направления')),
                ('new', models.BooleanField(db_index=True, default=True, verbose_name='Новое напрвление')),
                ('general_id_bx', models.IntegerField(verbose_name='ID направления в BX24 (для совместимости со старыми направлениями)')),
            ],
            options={
                'verbose_name': 'Направление сделки',
                'verbose_name_plural': 'Направления сделок',
            },
        ),
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calendar', models.DateField(unique=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('week', 'Не рабочий день'), ('work', 'Рабочий день')], default='work', max_length=4, verbose_name='Статус дня (рабочий/нерабочий)')),
            ],
            options={
                'verbose_name': 'День из роизводственного календаря',
                'verbose_name_plural': 'Производственный календарь',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID пользователя в BX24')),
                ('LAST_NAME', models.CharField(blank=True, max_length=35, null=True, verbose_name='Фамилия')),
                ('NAME', models.CharField(blank=True, max_length=35, null=True, verbose_name='Имя')),
                ('UF_DEPARTMENT', models.PositiveIntegerField(db_index=True, verbose_name='ID департамета')),
                ('ACTIVE', models.BooleanField(db_index=True, default=True, verbose_name='Пользователь активен (не уволен)')),
                ('URL', models.URLField(blank=True, max_length=150, null=True, verbose_name='URL пользователя')),
                ('STATUS_DISPLAY', models.BooleanField(db_index=True, default=True, verbose_name='Вывод пользователя в статистике подразделения')),
                ('ALLOWED_EDIT', models.CharField(choices=[('0', 'Запрещено'), ('1', 'Ограниченно разрешено'), ('2', 'Разрешено')], default='0', max_length=1, verbose_name='Доступ к редактированию данных')),
                ('ALLOWED_SETTING', models.BooleanField(default=False, verbose_name='Доступ к настройкам приложения')),
                ('ALLOWED_STATUS_DAY', models.BooleanField(default=False, verbose_name='Доступ к изменению статуса дня')),
                ('ALLOWED_VERIFICATION_MSG', models.BooleanField(default=False, verbose_name='Доступ к верификации сообщений')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID стадии в BX24')),
                ('STATUS_ID', models.CharField(db_index=True, max_length=35, verbose_name='Аббревиатура стадии сделки')),
                ('NAME', models.CharField(max_length=150, verbose_name='Название стадии сделки')),
                ('won', models.BooleanField(db_index=True, default=False, verbose_name='Сделка завершена успешно')),
                ('status', models.CharField(blank=True, choices=[('PREPARATION', 'Подготовка к работе'), ('WORK', 'В работе'), ('WON', 'Успешна'), ('FAILURE', 'Провалена')], db_index=True, max_length=11, null=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='dataapp.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Стадия сделки',
                'verbose_name_plural': 'Стадии сделки',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CALL_ID', models.CharField(db_index=True, max_length=75, unique=True, verbose_name='ID звонка в BX24')),
                ('CALL_TYPE', models.CharField(choices=[('1', 'Исходящий'), ('2', 'Входящий'), ('3', 'Входящий с перенаправлением'), ('4', 'Обратный звонок')], max_length=1, verbose_name='Тип звонка')),
                ('PHONE_NUMBER', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('CALL_DURATION', models.PositiveIntegerField(db_index=True, null=True, verbose_name='Длительность звонка')),
                ('CALL_START_DATE', models.DateTimeField(db_index=True, verbose_name='Дата начала звонка')),
                ('CRM_ACTIVITY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone', to='dataapp.activity', verbose_name='Дело')),
                ('PORTAL_USER_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone', to='dataapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='id сделки в BX24')),
                ('TITLE', models.CharField(blank=True, max_length=350, null=True, verbose_name='Название сделки')),
                ('DATE_CREATE', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания сделки')),
                ('DATE_MODIFY', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего изменения')),
                ('CLOSEDATE', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения сделки')),
                ('date_last_communication', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней коммуникации')),
                ('CLOSED', models.BooleanField(default=False, verbose_name='Сделка завершена')),
                ('opportunity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Сумма сделки')),
                ('balance_on_payments', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Остаток по оплатам')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Всего оплат на сумму')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Сделка активна (не удалена)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='dataapp.company', verbose_name='Компания')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='dataapp.direction', verbose_name='Направление')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='dataapp.stage', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='ASSIGNED_BY_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='dataapp.user', verbose_name='Ответственый в BX24'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateField(db_index=True, verbose_name='Дата комментария')),
                ('date_comment_add', models.DateTimeField(db_index=True, verbose_name='Дата добавления комментария')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('verified', models.BooleanField(default=False, verbose_name='Комментарий подтвержден')),
                ('date_verified', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to='dataapp.user', verbose_name='Комментатор')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='dataapp.user', verbose_name='Получатель')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by_user', to='dataapp.user', verbose_name='Пользователь который подтвердил комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='COMPANY_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='dataapp.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='activity',
            name='RESPONSIBLE_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='dataapp.user', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='CallsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_calls', models.IntegerField(blank=True, null=True, verbose_name='Количество звонков')),
                ('plan_completed', models.BooleanField(default=False, verbose_name='План на день выполнен')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_plan', to='dataapp.productioncalendar', verbose_name='Дата из производственного календаря')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_plan', to='dataapp.user', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'План по звонкам на день (NEW)',
                'verbose_name_plural': 'План по звонкам (NEW)',
                'unique_together': {('calendar', 'employee')},
            },
        ),
    ]
