# Generated by Django 4.1.2 on 2023-01-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='COMPANY_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='dataapp.company', verbose_name='Компания'),
        ),
    ]
