# Generated by Django 4.1.5 on 2023-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='ID',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='id сделки в BX24'),
        ),
    ]
