# Generated by Django 4.1.2 on 2023-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_alter_activity_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Компания активна (не удалена)'),
        ),
    ]
