# Generated by Django 4.1.2 on 2023-01-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_company_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ASSIGNED_BY_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='dataapp.user', verbose_name='Ответственый в BX24'),
        ),
    ]
