# Generated by Django 4.1.2 on 2023-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_alter_company_assigned_by_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Сделка активна (не удалена)'),
        ),
    ]
