# Generated by Django 4.1.2 on 2023-01-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0006_alter_stage_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='company',
        ),
    ]
