# Generated by Django 4.1.2 on 2023-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0007_remove_phone_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='URL',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='URL пользователя'),
        ),
    ]
